# Site settings
title: Simon Hsia
description: "A little notes."
url: "http://simonhsia.github.io"

# Build settings
permalink: pretty
paginate: 5
timezone: Asia/Shanghai
future: true
pygments: true
markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class